use career_db;
SET NAMES utf8mb4;

INSERT INTO category (`category_id`,`name`,`goal`) VALUES ('category_00','振り返り力','振り返り能力は行動を改善し、物事を前進させていくために必要なスキルです。全ての人におススメですが、特に「何をやってもうまくいかない」や「成長をなかなか実感できていない」という人におすすめのカテゴリです。またアプリ内の振り返り機能をフルに使えるようになる事で、より効果的な学習が可能になります。思考力との相性がいいです。');
INSERT INTO category (`category_id`,`name`,`goal`) VALUES ('category_01','自己分析','自己分析は自分の快楽と苦痛を知ることで自分が進むべき道（目標）を明らかにする行為です。就活をやっている人だけでなく、全ての人がすぐにやるべき内容です。自分のやりたいことが見つかったり、相手の視点に立って物事を考えられるようになります。');
INSERT INTO category (`category_id`,`name`,`goal`) VALUES ('category_02','選考対策','就活の準備としてやっておいた方が良いことがまとめられています。本選考やインターン選考に進む予定がある人はやるべきです。大切な機会を棒に振るわないようにしましょう。');
INSERT INTO category (`category_id`,`name`,`goal`) VALUES ('category_03','思考力','思考力とは問題を発見し問題解決の過程を考え、最適な選択肢を判断する力です。全ての人が優先的にやる必要があります。振り返りで見つかった問題をうまく解決できたり、物事の本質を見極めたりできるようになります。振り返り力と相性がいいです。');

INSERT INTO action (`action_id`,`category_id`,`title`,`content`,`standard_time`,`action_type`,`url`,`after`) VALUES ('action_0000','category_00','振り返りのアクションをするモチベーションを付けよう。','ネットの記事を調べ振り返りの重要性を認識し、なぜ自分に必要なのかをまとめよう。そしてその答えは振り返りの「やったこと」欄に記述しよう」','45分',2,'https://www.katsuiku-academy.org/media/effectivereflection/','振り返りのスキルを磨こうというモチベができることを目指しましょう。');
INSERT INTO action (`action_id`,`category_id`,`title`,`content`,`standard_time`,`action_type`,`url`,`after`) VALUES ('action_0001','category_00','メンターがフィードバックをしやすい振り返りの心構え。','メンターの気持ちになって振り返りを書いてみよう。評価するのに必要な情報が含まれているか、論点はどこかを考えて行うと非常に有効です。例としてあなたが味噌汁をつくったとして、振り返りを書きましょう。','15分',2,'','メンターへの気遣いができるようになりましょう。');
INSERT INTO action (`action_id`,`category_id`,`title`,`content`,`standard_time`,`action_type`,`url`,`after`) VALUES ('action_0002','category_00','振り返りのフレームワークを知ろう。','振り返りをより効率よく行うためのフレームワークを参考URLの記事をみて勉強しよう。そして、好きなフレームワークを一つ選び、昨日の行動に対してQOLを向上させることを目的として振り返りをしよう。','30分',2,'https://www.kikakulabo.com/tpl-reflection/','世の中にある洗練された振り返り方法があることを知り、形だけでも使えるようになることを目指しましょう。');
INSERT INTO action (`action_id`,`category_id`,`title`,`content`,`standard_time`,`action_type`,`url`,`after`) VALUES ('action_0003','category_00','PDCAサイクルを強化しよう。','あなたが最近提出した学校の課題に対してPDCAを回してみよう。「やったこと」欄に以下のP~Aまでの4項目を書きましょう。P...何が目的でどのような行動をしたのか。D...計画を実行する。C...実行して得られた結果とアクションの目的を比較し、不足している部分を明らかにする。A...不足分を補えるアクションに修正する。（そして実行する。）反省欄には今回自分が行ったPDCAの回し方の反省をしましょう。','60分',2,'','あなたのPDCAサイクルにおいて、改善ポイントを見つけることを目指しましょう。');
INSERT INTO action (`action_id`,`category_id`,`title`,`content`,`standard_time`,`action_type`,`url`,`after`) VALUES ('action_0004','category_00','①振り返りの「やったこと」欄の質を高めよう。','「学生時代に最も力を入れたこと」を書く作業でどのようなことをやったのかを「やったこと」欄に書きましょう。その際に①何が目的で②具体的にどのようなアクションを③どんなことに意識しながら行ったのかを示してください。','60分',0,'','やったことを反省に繋げやすくなることを目指しましょう。');
INSERT INTO action (`action_id`,`category_id`,`title`,`content`,`standard_time`,`action_type`,`url`,`after`) VALUES ('action_0005','category_00','②振り返りの「次のアクション」欄の質を高めよう。','「学生時代に最も力を入れたこと」を書く作業の反省でみつかった問題点を解決するために必要なアクションを次のアクション欄に書きましょう。反省で見つかった問題点を解消する方法は無数にありますが、その中からより適したアクションを選択しその理由も付けれるようにしましょう。','60分',0,'https://infinity-agent.co.jp/lab/logic-tree/','なぜそのネクストアクションを選択したのかを説明できることを目指しましょう。');
INSERT INTO action (`action_id`,`category_id`,`title`,`content`,`standard_time`,`action_type`,`url`,`after`) VALUES ('action_0006','category_00','③振り返りの「反省」欄の質を高めよう。','「学生時代に最も力を入れたこと」を書く作業での反省点を書きましょう。ここではアクションのゴールを達成した場合でも達成していない場合でもその理由を書きましょう。','60分',0,'','次のアクションに繋がる反省ができるようになることを目指しましょう。');
INSERT INTO action (`action_id`,`category_id`,`title`,`content`,`standard_time`,`action_type`,`url`,`after`) VALUES ('action_0100','category_01','自己分析① 自己分析を知ろう！','以下のurlの記事を読んで自己分析の意義、自己分析では何をやるのかのイメージをつけましょう。','30分',2,'https://note.com/maron0917/n/n9d554d1fd90b','自己分析が就活のためだけではなく、人生においても重要という感覚を持ち、自己分析を行うモチベーションがつくられることを目指しましょう。。');
INSERT INTO action (`action_id`,`category_id`,`title`,`content`,`standard_time`,`action_type`,`url`,`after`) VALUES ('action_0101','category_01','自己分析② 自分の中で一番大事にしている価値観を仮定しよう！','自分の一番深い位置にある価値観（憧れられたい、自信を付けたい等）を仮定してみましょう。また、仮定した価値観がなぜ生まれたのか（原因）を示すエピソードを探してみよう。','60分',1,'https://note.com/maron0917/n/n9d554d1fd90b','自分が仮定した価値観への納得度が50%以上になることを目指しましょう。');
INSERT INTO action (`action_id`,`category_id`,`title`,`content`,`standard_time`,`action_type`,`url`,`after`) VALUES ('action_0102','category_01','自己分析③ 仮定した根源的欲求を掘り下げてみよう！','「自己分析②」で仮定した価値観よりも奥にある価値観がある可能性があります。仮定した価値観をなぜ満たしたいのか（目的）を自問自答してみましょう。','60分',1,'https://note.com/maron0917/n/n9d554d1fd90b','自分が仮定した価値観への納得度が70%以上になることを目指しましょう。');
INSERT INTO action (`action_id`,`category_id`,`title`,`content`,`standard_time`,`action_type`,`url`,`after`) VALUES ('action_0103','category_01','自己分析④ 深掘りされた9つの価値観のどれに当てはまりそうか考えてみよう！','以下のurlの記事にある9種類の根源的欲求を把握し、深掘りした価値観がどれに当てはまるのか見てみよう。当てはまりそうにない場合は、まだ深掘りの余地があるかも知れないです。','60分',1,'https://note.com/maron0917/n/n9d554d1fd90b','9種類の根源的欲求に対して自分なりに優先順位を付けることを目指しましょう。');
INSERT INTO action (`action_id`,`category_id`,`title`,`content`,`standard_time`,`action_type`,`url`,`after`) VALUES ('action_0104','category_01','自己分析⑤ 根源的欲求のルーツを探ろう！','自分の根源的欲求はなにがきっかけでうまれたのか（原因）を知りましょう。自分の家庭環境や子供のころの印象に残っているエピソードは説得力が強いです。','60分',1,'https://note.com/maron0917/n/n9d554d1fd90b','仮定した根源的欲求への納得度が50%以上になることを目指しましょう。');
INSERT INTO action (`action_id`,`category_id`,`title`,`content`,`standard_time`,`action_type`,`url`,`after`) VALUES ('action_0105','category_01','自己分析⑥ 自分の欲求に基づく一貫した行動を一言で表してみよう！','色々なエピソードを振り返り、一貫している部分を言語化してみましょう。例「安定していたい」 → 「何かに依存しないでも生きていけるように自分を磨く」等','60分',1,'https://note.com/maron0917/n/n9d554d1fd90b','自分の一貫している軸が言語化できることによって、根源的欲求の納得度を上げることを目指しましょう。');
INSERT INTO action (`action_id`,`category_id`,`title`,`content`,`standard_time`,`action_type`,`url`,`after`) VALUES ('action_0106','category_01','自己分析⑦ 自分が定義した根源的欲求の納得度を90%以上にしよう！','過去の特徴的なエピソードにおける自分の動機が遠回しにでも根源的欲求に結び付いているかどうかを確認してみましょう。また、価値観が動機となって形成された自分の強みを探ってみましょう。例「なにかに依存しないでも生きていける能力を磨く」 → 強みは「ストイック」や「上昇志向」等。','30分',1,'https://note.com/maron0917/n/n9d554d1fd90b','自分の強みを根拠をもって話せるようになることを目指しましょう。');
INSERT INTO action (`action_id`,`category_id`,`title`,`content`,`standard_time`,`action_type`,`url`,`after`) VALUES ('action_0107','category_01','自己分析⑧ 働くことで成し遂げたいことを見つける方法の流れを知ろう！','urlの記事の「あなたが人生をかけて成し遂げたいことは何か」を読んでアウトラインを把握しましょう。','30分',1,'https://note.com/maron0917/n/n9d554d1fd90b','働くことで成し遂げたいことを決める際になにをすればいいかわからない状態を抜け出すことを目指しましょう。');
INSERT INTO action (`action_id`,`category_id`,`title`,`content`,`standard_time`,`action_type`,`url`,`after`) VALUES ('action_0108','category_01','自己分析⑨ 根源的欲求から働くことで成し遂げたいこと見つけてみよう！','自分の根源的欲求が満たされない状況や要因を挙げてみましょう。なるべく抽象度の高いものが良いです。例「安定していたい」→「安定を構成する要因を自分でコントロールできない状態」等。難しいので何回も壁打ちするのがいいと思います。','120分',1,'https://note.com/maron0917/n/n9d554d1fd90b','例のように自分なりの言葉で、そして抽象度の高いものを挙げられることを目指しましょう。難しければ要因を複数個挙げることを目指しましょう。');
INSERT INTO action (`action_id`,`category_id`,`title`,`content`,`standard_time`,`action_type`,`url`,`after`) VALUES ('action_0109','category_01','自己分析⑩ 自分にとって重要な問題を解決する手段を決めよう！','「自己分析⑨」で挙げた問題を解決する手段を複数個挙げてみよう。その中から自分が一番モチベーションを維持できそうなモノを選びましょう。モチベーションに関しては参考リンク内のモチベーションの構成図を参考にしてください。','120分',1,'https://note.com/maron0917/n/n905030b895b5','自分のモチベーションを最も引き出せる目標を見つけることを目指しましょう。');
INSERT INTO action (`action_id`,`category_id`,`title`,`content`,`standard_time`,`action_type`,`url`,`after`) VALUES ('action_0110','category_01','自己分析⑪ 目標を自分のモノにしよう！（オプション）','「自己分析⑩」で挙げた目標を自分の言葉で表現しよう。あなただからこそ出てくる言葉で表現しよう。','60分',1,'https://note.com/maron0917/n/n9d554d1fd90b','働くことで成し遂げたいことを自分の言葉で表現できることを目指しましょう。');
INSERT INTO action (`action_id`,`category_id`,`title`,`content`,`standard_time`,`action_type`,`url`,`after`) VALUES ('action_0111','category_01','自己分析⑫ ビジョンを実現する方法をイメージしよう！','具体的にどんな業界があって、それぞれがどのような課題にアプローチしているのか、それによってどのような影響を与えるかを調べてみましょう。','60分',1,'https://note.com/maron0917/n/n9d554d1fd90b','ビジョン達成するための手段を仕事に落とし込むことを目指しましょう。');
INSERT INTO action (`action_id`,`category_id`,`title`,`content`,`standard_time`,`action_type`,`url`,`after`) VALUES ('action_0112','category_01','自己分析⑬ 自分が決めたビジョンを合理化してみよう！','仮定した「働くことで成し遂げたいこと」のやる意義を3つ見つけましょう。合理化することで自信を持つことができ、モチベーション維持に大きく影響します。','60分',1,'https://note.com/maron0917/n/n9d554d1fd90b','自分が決めたビジョンに対して他人に話せるくらいに自信を持てることを目指しましょう。');
INSERT INTO action (`action_id`,`category_id`,`title`,`content`,`standard_time`,`action_type`,`url`,`after`) VALUES ('action_0116','category_01','他人と自己分析をして、自分の強みと弱みを相対的に評価しよう！','自分の強みや弱みが他者と完全に一致することは無いので、どのように違うのかを細かく分析してみましょう。また、他人の強みや弱みを知ることで相場感というものを付けることができるとなおよいです。','30分',1,'','自分の強みの固有性を話せるようになることを目指しましょう。');
INSERT INTO action (`action_id`,`category_id`,`title`,`content`,`standard_time`,`action_type`,`url`,`after`) VALUES ('action_0117','category_01','自分の3年後までのキャリアプランを仮定してみよう！','自分の人生の目標から逆算して3年後までにはどのようになっていなければいけないのかを400字以内でまとめてみましょう。気になる企業の社員インタビューを見るとイメージが付くかもしれません。','180分',1,'','業界や職業、役職等まで明確になっていることを目指しましょう。');
INSERT INTO action (`action_id`,`category_id`,`title`,`content`,`standard_time`,`action_type`,`url`,`after`) VALUES ('action_0118','category_01','プロフィールを埋めてみよう！','プロフィール欄を埋めてみよう。振り返りの「やったこと」欄に自己紹介の内容を書きましょう。「反省」欄と「次のアクション」欄は特になしでも大丈夫です。','15分',0,'','希望している業界や職業を埋めることと、30秒程度で伝えられる文量の自己紹介を書くことを目指しましょう。');
INSERT INTO action (`action_id`,`category_id`,`title`,`content`,`standard_time`,`action_type`,`url`,`after`) VALUES ('action_0200','category_02','学生時代頑張ったことを書いてみよう！','ESや面接で聞かれる「学生時代頑張ったこと」を400文字で書いてみましょう。ここでは自分の人間性や将来のビジョンと一貫性を持たせた内容にするのが理想です。また結論ファーストを意識することと、構成はPDCAを回していることが分かるように書きましょう。振り返りの「やったこと」欄に学チカを400字以内で記入してください。','180分',0,'https://shukatsu-mirai.com/archives/88839','自分がどれくらい頑張れているのかを把握することを目指しましょう。理想は次のアクションプランが見つかることです。');
INSERT INTO action (`action_id`,`category_id`,`title`,`content`,`standard_time`,`action_type`,`url`,`after`) VALUES ('action_0201','category_02','自分が気になる業界の課題を見つけよう！','自分が気になる業界を一つ挙げ、その業界が解決しようとしている問題やその業界自体の問題を3つ挙げよう。そして自分がその問題を解決することに魅力を感じるかどうかを直感的に考察してみよう。','60分',2,'https://gyokai-search.com/','自分が興味を持っている企業や業界を志す一つの理由が見つかることを目指しましょう。');
INSERT INTO action (`action_id`,`category_id`,`title`,`content`,`standard_time`,`action_type`,`url`,`after`) VALUES ('action_0202','category_02','自己PRを書いてみよう！','面接やESでよく聞かれる自己PRを400文字で考えましょう。自己分析で深掘りした内容を人に伝えられる形に整理しよう。結論ファーストや、伝わりやすい構成を意識しながら作りましょう。また、一番伝えたいことをあらかじめ決めておけばコンパクトにまとまると思います。振り返りの「やったこと」欄に自己PRを400字以内で記入してください。','180分',2,'https://www.kurihaku.jp/2021/special/entrysheet/464/','自分の魅力を把握し、業界、企業選びの一つの軸ができることを目指しましょう。');
INSERT INTO action (`action_id`,`category_id`,`title`,`content`,`standard_time`,`action_type`,`url`,`after`) VALUES ('action_0203','category_02','志望企業の面接の質問内容を知ろう。','ネット検索で志望企業でどんな質問をされているかを調べ、自分なりの回答を簡易的に作ろう。','45分',2,'https://syukatsu-kaigi.jp/','面接で聞かれうる質問を把握している状態になることを目指しましょう。理想はいろんな質問に対しても一貫した回答ができるようになることです。');
INSERT INTO action (`action_id`,`category_id`,`title`,`content`,`standard_time`,`action_type`,`url`,`after`) VALUES ('action_0204','category_02','あなたの弱みを語ろう！','あなたの弱みを400文字で書こう。結論ファーストを意識することと、弱みを克服するためにどのようにアクションをしているか、またはする予定かもまとめましょう。振り返りの反省の部分に400文字以内で記入してください。','180分',2,'url','自分の欠点を把握し、どのように克服していくかのアクションプランが立てれることを目指しましょう。');

INSERT INTO user (`user_id`,`email`,`password`,`status`) VALUES ('709e07db-5837-451e-a2d2-265bdc8f8a73','allofcareer@gmail.com','$2a$10$mwhkDb2bg6ARnHi29BPbTuHZwEETyUUbIf/WpDbFuii9AJNxwj04K',75392);
